### PR TITLE
Removed deprecated function in dashboard_api.py

### PR DESCRIPTION
**Pull request by yashpal2104**

### CODE REVIEW

**Comment by fatchat** [comment]
too small for a PR

**Comment by yashpal2104** [comment]
@fatchat is it too small of a PR if I have removed a deprecated functions(in the commit 1) and unused imports(in commit 2) because I have done that in my PR, if there is an error in removing the deprecated functions(in my commit 1) you can say so but I am unable to understand how this is a small contribution PR?

**Comment by fatchat** [comment]
my mistake, i was looking only at the [first commit](https://github.com/DalgoT4D/DDP_backend/pull/829/commits/7d834372f31209effc4aa5ccd362a60ec87e026a)

now i see the entire PR i'm even more worried... what made you think this function was deprecated? we call it from our frontend

**Comment by yashpal2104** [comment]
Isn't it mentioned here. get_prefect_dataflows_v1
Screenshot 2024-08-24 145356

**Pull request closed without merging**
