### PR TITLE
Removed the deprecated function used in the airbytehelpers.setup_airb…

### PR DESCRIPTION
**Pull request by yashpal2104**
Removed "airbytehelpers.setup_airbyte_workspace_v1"

Since in this the API entrypoint is given so I removed assignment of workspace from "airbytehelpers.setup_airbyte_workspace_v1 "to "None" plz see if this works I could not understand how do I test this. Thanks

### CODE REVIEW

**Comment by fatchat** [comment]
??? how could this possibly work
the very next line will crash when you reference `workspace.workspaceId`

**Comment by yashpal2104** [comment]
It did not raise any errors when I passed it through tests of deepsource ai

**Comment by fatchat** [comment]
@yashpal2104 please read the code and understand what i'm saying. i'm not getting into online arguments with strangers

**Comment by yashpal2104** [comment]
I am sorry @fatchat I don't intend to cause any inconveniences or arguments, I am extremely sorry if I made you think that way. I will surely try to solve this problem in the correct way. Thank you for pointing it out and giving your time to point out the error.

**Pull request closed without merging**
