### PR TITLE
Feature remove unused prefect

### LINKED ISSUE #542: remove unused prefect-related functions
## Description
The codebase contains deprecated code which needs to be removed. As a first step towards this, remove the functions by following the sheet 

https://docs.google.com/spreadsheets/d/1sgh5NtW8MEcYiUcs9GaojtqsTR2Vk_zpX5bF4ef6zzs/edit#gid=0

## Goals
- [ ] Remove unused functions 
- [ ] Remove related tests

## Expected Outcome
The program should still work, all tests should pass

## Acceptance Criteria
- [ ] Should follow the Google Sheet listed above
- [ ] Tests should pass

## Implementation Details
No new code is to be added

## Mockups / Wireframes
N/A

### Product Name
Dalgo

### Project Name
Dalgo

### Organization Name:
Project Tech4Dev

### Domain
30 Others

### Tech Skills Needed:
Python

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
Performance Improvement

### Sub Category
Backend, Deprecation, Technical Debt, Beginner friendly

### PR DESCRIPTION
**Pull request by hp77-creator**
Fixes #542 

@fatchat 
I tried running `pytest`
but got multiple `ModuleNotFoundError`, The errors are coming from files in which I haven't done any change.

logs from `pytest` were regarding missing `ddpui.assets.whitelist` file
is there any setup that we need to do before running tests?

### CODE REVIEW

**Comment by hp77-creator** [comment]
@fatchat @VedantKhairnar please check

**Comment by fatchat** [comment]
confirmed that functions removed are not being called 

@hp77-creator give us a few more days, the team is occupied with other tasks

**Comment by hp77-creator** [comment]
Its alright @fatchat 
Happy to help

**Comment by Ishankoradia** [comment]
Ran all the test cases. 
Thanks @hp77-creator for your contribution. 
Will update our github ci workflow so forked PRs can run them, currently it is not so.

**Review by Ishankoradia — APPROVED** [review]

**Pull request merged**
